// Define Action type
export const USER_ACTION_TYPE = {
   SET_CURRENT_USER: 'SET_CURRENT_USER',
   SET_CATEGORIES: 'SET_CATEGORIES',
   SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
   SET_CART_ITEMS: 'SET_CART_ITEMS'
}